# Generated by Django 4.1.7 on 2023-02-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto_pers', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=2000)),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='League_of_Legends.roles')),
            ],
        ),
    ]
